[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "JEPADepth"
dynamic = ["version"]
authors = [
    { name = "Ionut-Orlando Grigore-Atimut", email = "ionut.grigore@cs.upt.ro" }
]

description = "JEPADepth: Some title I need to think."
readme = "README.md"
requires-python = ">=3.8"

dependencies = [
    TODO: add here
]

[project.optional-dependencies]
dev = [
    TODO: add here
]

[tool.setuptools.packages.find]
include = ["src"]
exclude = ["notebooks"]