# models
# -----------
model_name: "pixio" 
num_input_channels: 3  # number of input channels of the input image(s)
num_output_channels: 1
pose_cnn_weights_path: null
monodepth2_pose_cnn_weights_path: null
pixio:
  encoder: "pixio_vith16" # choices=["pixio_vitb16", "pixio_vitl16", "pixio_vith16"]
  pretrained_ckp: null
resnet_pose_cnn:
  num_layers: 18
  pretrained: True
  num_input_images: 2
  num_input_features: 1
  num_frames_to_predict_for: 2


# misc
# -----------
data_path: '/data/backup_gpu2/home/ionut/JEPADepth/data/kitti/kitti_data'
tensorboard_path: '/data/backup_gpu2/home/ionut/JEPADepth/tensorboard'
pretrained_models_folder: '/data/backup_gpu2/home/ionut/JEPADepth/src/tensorboard/train/...'
image_path_inference: '/data/backup_gpu2/home/ionut/JEPADepth/src/inference/input_images/img1.png'
                     # I can also give an entire folder with images, not just one image!
                     # choices: ['/data/backup_gpu2/home/ionut/JEPADepth/src/inference/input_images/img1.png',
                     #           '/data/backup_gpu2/home/ionut/JEPADepth/src/inference/input_images']
image_extension_inference: "png"
use_cuda: True
clip_grad_norm: False
num_workers: 4
im_sz: [320, 1024] # [320, 1024], [192, 640] -> H W
bs: 12

# training
# -----------
training_dataset: "kitti" # dataset to train on; choices=["kitti", "kitti_odom", "kitti_depth", "kitti_test", "cityscapes_preprocessed", "nyu_raw"])
num_epochs: 20 # number of epochs for training.
training_split: "eigen_zhou" # which training split to use;  choices=["eigen_zhou", "eigen_full", "odom", "benchmark", "cityscapes_preprocessed", "nyu_raw"],
learning_rate: 0.0001 # 1e-4
scheduler_step_size: 15 # step size of the scheduler used for training.
weight_decay: 0.01 # 1e-4
use_stereo_training: False # if set, uses stereo pair for training.
frame_ids_training: [0, -1, 1] # frames to use for training (current, previous and next); choices: [0, -1, 1], [0, 1]
pose_model_input: "pairs" # how many images the pose network gets; choices=["pairs", "all"]
load_pretrained_depth_model: False # if set, uses pretrained encoder and depth decoder for training (both of them!).
load_pretrained_pose_model: False # if set, uses pretrained PoseNet for training.
train_from_png: False # if set, trains from raw KITTI png files (instead of jpgs).
use_different_learning_rate: False # if set, uses different learning rate for training.
save_frequency: 1 # number of epochs between each save.
log_frequency: 10 # number of batches between each tensorboard log.
pose_model_type: resnet_pose_cnn # choices=["posecnn", "resnet_pose_cnn"]
models_to_load: ["encoder", "depth", "pose_encoder", "pose"]
disparity_smoothness_weight: 0.001 # 1e-3
use_ssim: True # if set, uses SSIM in the loss. This is kinda always True
monodepthv1_multiscale: False # if set, uses Monodepthv1 multiscale. This is kinda always False
disable_automasking: False # if set, doesn't do auto-masking.
use_average_reprojection: False # if set, uses average reprojection loss. We use minimum reprojection loss as described in "Diging into Self-Supervised MDE"
#NOTE: I should play with the terms below in order to find the right configuration!
loss_scales: [0] # scales used in the loss; choices: [0]; [0, 1, 2, 3]
min_depth: 0.1 # 0.01, 0.1
max_depth: 100.0 # 80.0, 100.0


# evaluation
# -----------
evaluation_split: eigen #choices=["eigen", "eigen_benchmark", "benchmark", "odom_9", "odom_10", "cityscapes"]
evaluation_mode: mono # choices=["mono", "stereo"]
evaluation_post_process: True # if set will perform the flipping post processing from the original Monodepth paper.
                              # "Unsupervised Monocular Depth Estimation With Left-Right Consistency", pg.5, bottom-right.
prediction_depth_scale_factor: 1 # if set multiplies predictions by this number.
save_predicted_disparities: False # if set saves predicted disparities.
numpy_disparities_to_evaluate:  # optional path to a .npy disparities file to evaluate.
evaluate_eigen_to_benchmark: False # if set assume we are loading eigen results from .npy but we want to evaluate using the new benchmark.
no_evaluation: False # if set disables evaluation
disable_median_scaling: False # if set disables median scaling in evaluation.