model_name: "mambaDepthEnc_320x1024" # mambaDepthBot_320x1024


# model
# -----------
num_input_channels: 3  # number of input channels of the input image(s)
num_output_channels: 1
deep_supervision: True # this is basically for creating disparity heads at different scales in the decoder.
unet_base_num_features: 32
unet_max_num_features: 512
n_conv_per_stage_encoder: [2, 2, 2, 2, 2, 2, 2]
n_conv_per_stage_decoder: [2, 2, 2, 2, 2, 2]
conv_kernel_sizes: [[3, 3], [3, 3], [3, 3], [3, 3], [3, 3], [3, 3], [3, 3]]
pool_op_kernel_sizes: [[1, 1], [2, 2], [2, 2], [2, 2], [2, 2], [2, 2], [2, 2]]


# misc
# -----------
data_path: '/data/disertatie/kitti'
tensorboard_path: '/data/disertatie/MambaDepth/src/tensorboard'
pretrained_models_folder: '/data/disertatie/MambaDepth/src/tensorboard/train/mambaDepthBot_320x1024/20240201-214842/models/weights_epoch_7'
image_path_inference: '/data/disertatie/MambaDepth/src/inference/input_images/img1.png'
                     # I can also give an entire folder with images, not just one image!
                     # choices: ['/data/disertatie/MambaDepth/src/inference/input_images/img1.png',
                     #          '/data/disertatie/MambaDepth/src/inference/input_images']
image_extension_inference: "png"
use_cuda: True
device: ['cuda:0', 'cuda:1', 'cuda:2', 'cuda:3', 'cuda:4', 'cuda:5', 'cuda:6', 'cuda:7']
num_workers: 8
ndevices: 4
im_sz: [320, 1024] # [320, 1024], [192, 640] -> H W
bs: 12

# training
# -----------
training_dataset: "kitti" # dataset to train on; choices=["kitti", "kitti_odom", "kitti_depth", "kitti_test", "cityscapes_preprocessed", "nyu_raw"])
num_epochs: 20 # number of epochs for training.
training_split: "eigen_zhou" # which training split to use;  choices=["eigen_zhou", "eigen_full", "odom", "benchmark", "cityscapes_preprocessed", "nyu_raw"],
learning_rate: 0.0001 # 1e-4
scheduler_step_size: 15 # step size of the scheduler used for training.
use_stereo_training: False # if set, uses stereo pair for training.
frame_ids_training: [0, -1, 1] # frames to use for training (current, previous and next); choices: [0, -1, 1], [0, 1]
pose_model_input: "pairs" # how many images the pose network gets; choices=["pairs", "all"]
load_pretrained_model: False # if set, uses pretrained encoder and depth decoder for training (both of them!).
load_pretrained_pose: False # if set, uses pretrained PoseNet for training.
train_from_png: True # if set, trains from raw KITTI png files (instead of jpgs).
use_different_learning_rate: False # if set, uses different learning rate for training.
save_frequency: 1 # number of epochs between each save.
log_frequency: 10 # number of batches between each tensorboard log.
pose_model_type: separate_resnet # choices=["posecnn", "separate_resnet", "shared"]
models_to_load: ["encoder", "depth", "pose_encoder", "pose"]
disparity_smoothness_weight: 0.001 # 1e-3
use_ssim: True # if set, uses SSIM in the loss. This is kinda always True
monodepthv1_multiscale: False # if set, uses Monodepthv1 multiscale. This is kinda always False
disable_automasking: False # if set, doesn't do auto-masking.
use_average_reprojection: False # if set, uses average reprojection loss. We use minimum reprojection loss as described in "Diging into Self-Supervised MDE"
#NOTE: I should play with the terms below in order to find the right configuration!
loss_scales: [0, 1, 2, 3] # scales used in the loss; choices: [0]; [0, 1, 2, 3]
min_depth: 0.1 # 0.01, 0.1
max_depth: 100.0 # 80.0, 100.0


# evaluation
# -----------
evaluation_split: eigen #choices=["eigen", "eigen_benchmark", "benchmark", "odom_9", "odom_10", "cityscapes"]
evaluation_mode: mono # choices=["mono", "stereo"]
evaluation_post_process: True # if set will perform the flipping post processing from the original Monodepth paper.
                              # "Unsupervised Monocular Depth Estimation With Left-Right Consistency", pg.5, bottom-right.
prediction_depth_scale_factor: 1 # if set multiplies predictions by this number.
save_predicted_disparities: False # if set saves predicted disparities.
numpy_disparities_to_evaluate:  # optional path to a .npy disparities file to evaluate.
evaluate_eigen_to_benchmark: False # if set assume we are loading eigen results from .npy but we want to evaluate using the new benchmark.
no_evaluation: False # if set disables evaluation
disable_median_scaling: False # if set disables median scaling in evaluation.