'''
Visualize the context and target masks generated by MBMaskCollator for I-JEPA training on KITTI.
'''

import torch
import torch.nn.functional as F
import matplotlib.pyplot as plt
from torch.utils.data import DataLoader

from src.utils import readlines
from src.datasets.kitti_dataset import KITTIRAWDataset
from src.masks.mask_collator import MaskCollator as MBMaskCollator

def visualize_masked_image(img, patch_size, mask_indices, alpha=0.85):
    """Visualize image with masked patches darkened via semi-transparent black overlay."""
    if mask_indices is None:
        return img

    C, H, W = img.shape

    num_patches_h = H // patch_size
    num_patches_w = W // patch_size

    # 1 = visible (keep), 0 = masked (darken)
    patch_mask = torch.zeros(num_patches_h * num_patches_w, device=img.device)
    patch_mask[mask_indices] = 1.0
    patch_mask = patch_mask.reshape(num_patches_h, num_patches_w)

    # Upsample to image resolution
    patch_mask = patch_mask.unsqueeze(0).unsqueeze(0)  # [1, 1, H_p, W_p]
    patch_mask = F.interpolate(patch_mask, size=(H, W), mode='nearest')
    patch_mask = patch_mask.squeeze(0)  # [1, H, W]

    # Blend: visible patches stay, masked patches darken with alpha blend toward black
    masked_img = img * patch_mask + img * (1 - patch_mask) * (1 - alpha)

    return masked_img

# Parameters
NUM_SAMPLES  = 5   # number of rows (one sample per row)
NUM_TARGETS  = 4   # number of target mask columns 
PATCH_SIZE   = 16
IMAGE_H      = 192
IMAGE_W      = 640

if __name__ == "__main__":

    # These are the same parameters used during training, so the masks we visualize here will reflect the actual masking strategy used for I-JEPA training on KITTI
    mask_collator = MBMaskCollator(
        input_size=(IMAGE_H, IMAGE_W),
        patch_size=PATCH_SIZE,
        enc_mask_scale=[0.85, 1.0],
        pred_mask_scale=[0.15, 0.2],
        aspect_ratio=[0.75, 1.5],
        nenc=1,
        npred=4,
        allow_overlap=False,
        min_keep=10,
    )

    train_filenames = readlines("data/kitti/kitti_splits/eigen_zhou/train_files.txt")
    dataset = KITTIRAWDataset(
        'data/kitti/kitti_data', train_filenames,
        IMAGE_H, IMAGE_W, [0, -1, 1], 4,
        is_train=True, img_ext='.jpg',
    )
    # Load one image per batch so each dataloader iteration = one row
    dataloader = DataLoader(dataset, batch_size=1, shuffle=True, num_workers=0, pin_memory=True, drop_last=True)

    # Collect samples
    samples = []   # list of (img, enc_mask, [tgt_mask_0, ..., tgt_mask_K-1])
    for batch_idx, inputs in enumerate(dataloader):
        imgs = inputs["color_aug", 0, 0]           # [1, 3, H, W]
        batch_list = [imgs[i] for i in range(imgs.shape[0])]
        _, masks_enc, masks_target = mask_collator(batch_list)

        img      = imgs[0]                          # [3, H, W]
        enc_mask = masks_enc[0]                     # context indices

        # masks_target is shaped [B * npred]; one block of npred masks per image
        tgt_masks = [masks_target[k] for k in range(NUM_TARGETS)]

        samples.append((img, enc_mask, tgt_masks))
        if len(samples) >= NUM_SAMPLES:
            break

    # ── Build figure ──────────────────────────────────────────────────────────
    # Columns: Original | Context | Target-0 | Target-1 | ... | Target-(K-1)
    n_cols  = 2 + NUM_TARGETS
    n_rows  = NUM_SAMPLES
    total_patches = (IMAGE_H // PATCH_SIZE) * (IMAGE_W // PATCH_SIZE)

    col_w = 3.2                                      # inches per column
    row_h = col_w * (IMAGE_H / IMAGE_W)              # keep image aspect ratio → ~0.96 in
    plt.rcParams.update({"font.family": "serif", "font.size": 9})
    fig, axes = plt.subplots(
        n_rows, n_cols,
        figsize=(col_w * n_cols, row_h * n_rows + 0.35),  # +0.35 for title row
        gridspec_kw={"wspace": 0.0, "hspace": 0.0},
    )
    # Ensure axes is always 2-D
    if n_rows == 1:
        axes = axes[None, :]

    for row_idx, (img, enc_mask, tgt_masks) in enumerate(samples):
        img_np = img.permute(1, 2, 0).clamp(0, 1).cpu().numpy()

        # --- col 0: original image ---
        axes[row_idx, 0].imshow(img_np)

        # --- col 1: context ---
        ctx_vis = visualize_masked_image(img, PATCH_SIZE, enc_mask)
        axes[row_idx, 1].imshow(ctx_vis.permute(1, 2, 0).clamp(0, 1).cpu().numpy())

        # --- cols 2+: targets ---
        for k, tgt_mask in enumerate(tgt_masks):
            tgt_vis = visualize_masked_image(img, PATCH_SIZE, tgt_mask)
            axes[row_idx, 2 + k].imshow(
                tgt_vis.permute(1, 2, 0).clamp(0, 1).cpu().numpy()
            )

        for ax in axes[row_idx]:
            ax.set_xticks([])
            ax.set_yticks([])
            ax.set_aspect("auto")   
            for spine in ax.spines.values():
                spine.set_visible(True)
                spine.set_edgecolor("black")
                spine.set_linewidth(1.2)

    # Column titles on top row: "Original", "Context", then a single "Targets" spanning all target columns
    axes[0, 0].set_title("Original", fontsize=28, fontweight="bold", color="#333333", pad=4)
    axes[0, 1].set_title("Context",  fontsize=28, fontweight="bold", color="#2196F3",  pad=4)

    # Single "Targets" title centered over all target columns using the middle target axis
    mid_target_col = 2 + (NUM_TARGETS - 1) // 2
    axes[0, mid_target_col].set_title("Targets", fontsize=28, fontweight="bold", color="#E64A19", pad=4)

    # Force zero gaps between all rows and columns
    title_frac = 0.35 / (row_h * n_rows + 0.35)     # fraction of figure height used by titles
    fig.subplots_adjust(left=0, right=1, top=1.0 - title_frac, bottom=0, wspace=0, hspace=0)

    fig.savefig(
        "assets/context_target_masking.png",
        dpi=300,
    )
    plt.show()
    print("Saved to assets/context_target_masking.png")
